### PR TITLE
fix/worker-debug

### PR DESCRIPTION
**Pull request by gratcliff**
Updated token location, cloudflare installation options, and req/res cloning

### CODE REVIEW

**Comment by domharrington** [comment]
I think it's useful to have bugsnag still in this repo, even if it's in a separate debug-template.js, just incase we have to use it again? Any way we can make it so that the user can toggle "debug" mode during install, or is this too confusing?

**Comment by gratcliff** [comment]
> I think it's useful to have bugsnag still in this repo, even if it's in a separate debug-template.js, just incase we have to use it again? Any way we can make it so that the user can toggle "debug" mode during install, or is this too confusing?

I don't think it's too confusing - the hesitation I have is where it's applied. If you'd like, I can add it back as a util function that can be deployed at will?

**Comment by domharrington** [comment]
Is there a way that you can think of where we could toggle it on and off at will in the install process, so we can get people to turn it on if they're having problems? We could add a dropdown to the install.json, but maybe it's too much if we think these runtime issues will be few and far between now we got that TLS 1.3 issue resolved?

**Comment by gratcliff** [comment]
> Is there a way that you can think of where we could toggle it on and off at will in the install process, so we can get people to turn it on if they're having problems? We could add a dropdown to the install.json, but maybe it's too much if we think these runtime issues will be few and far between now we got that TLS 1.3 issue resolved?

Wouldn't that be routing to their bugsnag? Meaning we'd need to get that key somehow (oauth all over again)?

**Comment by domharrington** [comment]
@gratcliff my intention was to route it to our bugsnag, so we can see runtime errors in the worker when it is running in their cloudflare account.

**Comment by domharrington** [comment]
Let me know if you want me to review this! Removing as a reviewer so I dont get pinged in Slack every day!

**Pull request closed without merging**
